columns:
  - User_ID: int
  - Product_ID: category
  - Gender: category
  - Age: category
  - Occupation: int
  - City_Category: category
  - Stay_In_Current_City_Years: category
  - Marital_Status: int
  - Product_Category_1: int
  - Product_Category_2: float
  - Product_Category_3: float
  - Purchase: int

numerical_columns:
  - User_ID
  - Occupation
  - Marital_Status
  - Product_Category_1
  - Product_Category_2
  - Product_Category_3
  - Purchase

categorical_columns:
  - User_ID
  - Product_ID
  - Gender
  - Age
  - City_Category
  - Stay_In_Current_City_Years


drop_columns:
  - User_ID
  - Product_ID

# for data transformation
or_columns:
  - Age

oh_columns:
  - City_Category

lab_columns:
  - Gender

impute_columns:
  - Product_Category_2
  - Product_Category_3

datatype_change_column:
  - Stay_In_Current_City_Years
